version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: funakun
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: research_time_log
    restart: always
    networks:
      - lesson
networks:
  lesson:
